"""
Django settings for feria_api project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9=%e^8+#8w5ey1+l+4_q!vo%$hs%yjzkb6oq(31$9du#s=it56'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    #'django.contrib.gis',        # soporte geoespacial
    'rest_framework',            # Django REST Framework
    'usuarios',                 # tabla usuarios
    'negocios',
    'suscripciones',
    'mapas',
    'catalogo',
    'ventas',
    'interacciones',
    'rutas',

    'rest_framework_gis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #para Render
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    #'core.middleware.firebase_auth.FirebaseAuthenticationMiddleware',
]

ROOT_URLCONF = 'feria_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'feria_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         #'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': os.environ.get('DB_NAME'),
#         'USER': os.environ.get('DB_USER'),
#         'PASSWORD': os.environ.get('DB_PASSWORD'),
#         'HOST': os.environ.get('DB_HOST'),
#         'PORT': os.environ.get('DB_PORT'),
#
#
#         #'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         #'NAME': 'feria16_db',        # nombre de la base que creaste
#         #'USER': 'postgres',          # tu usuario
#         #'PASSWORD': '1234',      # tu contraseña
#         #'HOST': 'localhost',
#         #'PORT': '5432',
#     }
# }

# Base de datos (Render)
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL')
    )
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
#para Render
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.Usuario'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'usuarios.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}




from pathlib import Path
import firebase_admin
from firebase_admin import credentials

# Si settings.py está en 'Feria16Backend/', BASE_DIR apunta a la carpeta inmediatamente superior (App16deJulio/apps/).
# Asumamos que BASE_DIR ya fue definido al inicio de settings.py
BASE_DIR = Path(__file__).resolve().parent.parent
# Si tu settings.py está en 'Feria16Backend', entonces 'BASE_DIR' es la carpeta anterior.

if not firebase_admin._apps:
    # 1. Ajuste de la ruta: Agregamos el subdirectorio 'firebase'
    cred_path = BASE_DIR / "firebase/en-la-16-de-julio-firebase-adminsdk-fbsvc-3846a84cfd.json"

    # 2. PRUEBA DE DEPURACIÓN:
    print("--- DEBUG FIREBASE PATH ---")
    print(f"Buscando credenciales en: {cred_path.as_posix()}")
    print(f"¿Existe el archivo? {cred_path.exists()}")
    print("---------------------------")

    try:
        # Usamos Path directamente, ya no necesitamos .as_posix()
        cred = credentials.Certificate(cred_path)
        firebase_admin.initialize_app(cred)
        print("Firebase inicializado exitosamente.")
    except Exception as e:
        print(f"ERROR AL INICIALIZAR FIREBASE (Credenciales): {e}")

