"""
Django settings for feria_api project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# ======================
# ENTORNO
# ======================
ENV = os.getenv("ENV", "local")

# ======================
# SEGURIDAD
# ======================
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")

DEBUG = ENV != "production"

ALLOWED_HOSTS = ["*"]

# ======================
# APLICACIONES
# ======================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'rest_framework',
    'rest_framework_gis',

    'usuarios',
    'negocios',
    'suscripciones',
    'mapas',
    'catalogo',
    'ventas',
    'interacciones',
    'rutas',
]

# ======================
# MIDDLEWARE
# ======================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ======================
# URLS / WSGI
# ======================
ROOT_URLCONF = 'feria_api.urls'
WSGI_APPLICATION = 'feria_api.wsgi.application'

# ======================
# BASE DE DATOS
# ======================
if ENV == "production":
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ.get("DATABASE_URL"),
            engine='django.contrib.gis.db.backends.postgis'
        )
    }
else:
    # Docker local
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': os.getenv('DB_NAME', 'feria16_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', '1234'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

# ======================
# PASSWORDS
# ======================
AUTH_PASSWORD_VALIDATORS = []

# ======================
# INTERNACIONALIZACIÓN
# ======================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ======================
# STATIC FILES
# ======================
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ======================
# MODELO USUARIO
# ======================
AUTH_USER_MODEL = 'usuarios.Usuario'

# ======================
# DRF
# ======================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'usuarios.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# ======================
# FIREBASE
# ======================
import firebase_admin
from firebase_admin import credentials
import json

if not firebase_admin._apps:

    try:
        if ENV == "production":
            # 🔥 desde variable de entorno (Render)
            firebase_json = os.getenv("FIREBASE_CREDENTIALS")

            if firebase_json:
                cred_dict = json.loads(firebase_json)
                cred = credentials.Certificate(cred_dict)
            else:
                raise Exception("FIREBASE_CREDENTIALS no definido")

        else:
            # 🔧 local (archivo)
            cred_path = BASE_DIR / "firebase/en-la-16-de-julio-firebase-adminsdk-fbsvc-3846a84cfd.json"
            cred = credentials.Certificate(cred_path)

        firebase_admin.initialize_app(cred)
        print("🔥 Firebase inicializado correctamente")

    except Exception as e:
        print(f"❌ Error Firebase: {e}")

