# Generated by Django 4.1.1 on 2026-03-26 20:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARTICULO_BASE',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RUBRO_BASE',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SUBRUBRO_BASE',
            fields=[
                ('id_subrubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('id_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='catalogo.rubro_base')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='rubro_base',
            index=models.Index(fields=['nombre'], name='catalogo_ru_nombre_2b3080_idx'),
        ),
        migrations.AddField(
            model_name='articulo_base',
            name='id_subrubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_base', to='catalogo.subrubro_base'),
        ),
        migrations.AddIndex(
            model_name='subrubro_base',
            index=models.Index(fields=['nombre'], name='catalogo_su_nombre_4ea786_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subrubro_base',
            unique_together={('id_rubro', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='articulo_base',
            index=models.Index(fields=['nombre'], name='catalogo_ar_nombre_2e996b_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo_base',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalogo_ar_search__2098e2_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='articulo_base',
            unique_together={('id_subrubro', 'nombre')},
        ),
    ]
