# Generated by Django 4.1.1 on 2025-12-16 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_ubicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEGOCIO',
            fields=[
                ('id_negocio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_negocio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userapp')),
            ],
        ),
    ]
