# Generated by Django 4.1.1 on 2026-01-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_ubicaciones_fecha_actualizacion_and_more'),
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negocio', to='usuarios.userapp'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['id_user'], name='negocios_ne_id_user_55de2c_idx'),
        ),
    ]
