# Generated by Django 4.1.1 on 2026-03-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0012_ubicaciones_geometria_user'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARTICULOS_VENTA',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('agotado', 'Agotado'), ('eliminado', 'Eliminado lógico')], max_length=20)),
                ('id_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='catalogo.articulo_base')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userapp')),
            ],
        ),
        migrations.CreateModel(
            name='OFERTAS',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.URLField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.articulos_venta')),
            ],
        ),
        migrations.CreateModel(
            name='GALERIA',
            fields=[
                ('id_galeria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('descripcion', models.CharField(max_length=255)),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.articulos_venta')),
            ],
        ),
        migrations.AddIndex(
            model_name='articulos_venta',
            index=models.Index(fields=['estado'], name='ventas_arti_estado_8913eb_idx'),
        ),
        migrations.AddIndex(
            model_name='articulos_venta',
            index=models.Index(fields=['id_articulo'], name='ventas_arti_id_arti_4853a1_idx'),
        ),
        migrations.AddIndex(
            model_name='articulos_venta',
            index=models.Index(fields=['id_user'], name='ventas_arti_id_user_9c675f_idx'),
        ),
    ]
