# Generated by Django 4.1.1 on 2026-03-26 20:39

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AREA',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_area', models.CharField(choices=[('Poligono', 'Polígono'), ('Polilinea', 'Polilínea')], max_length=50)),
                ('coordenadas', models.JSONField()),
                ('geometria', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(max_length=7)),
                ('id_articulo', models.ManyToManyField(blank=True, related_name='areas', to='catalogo.articulo_base')),
            ],
        ),
        migrations.CreateModel(
            name='AREA_VECINA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vecinos', to='mapas.area')),
                ('area_vecina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vecino_de', to='mapas.area')),
            ],
        ),
        migrations.AddIndex(
            model_name='area_vecina',
            index=models.Index(fields=['area'], name='mapas_area__area_id_57804f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='area_vecina',
            unique_together={('area', 'area_vecina')},
        ),
        migrations.AddIndex(
            model_name='area',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geometria'], name='mapas_area_geometr_6368b8_gist'),
        ),
    ]
