# Generated by Django 4.1.1 on 2025-10-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPP',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('proveedor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('rol', models.CharField(default='usuario', max_length=50)),
                ('ultimo_inicio', models.DateTimeField()),
            ],
        ),
    ]
