# Generated by Django 4.1.1 on 2025-10-21 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='UID',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='proveedor',
            field=models.CharField(choices=[('google', 'Google'), ('email', 'Correo Electrónico'), ('telefono', 'Teléfono')], default='google', max_length=50),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='ultimo_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
