# Generated by Django 4.1.1 on 2025-11-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_userapp_telefono_alter_userapp_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='estado',
            field=models.CharField(default='activo', max_length=10),
        ),
    ]
