# Generated by Django 4.1.1 on 2025-12-16 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_userapp_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UBICACIONES',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tipo', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userapp')),
            ],
        ),
    ]
