# Generated by Django 4.1.1 on 2026-01-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_ubicaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicaciones',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='usuarios.userapp'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='tipo',
            field=models.CharField(choices=[('fija', 'Fija'), ('movil', 'Móvil')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='ubicaciones',
            index=models.Index(fields=['id_user'], name='usuarios_ub_id_user_4f1560_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicaciones',
            index=models.Index(fields=['latitud', 'longitud'], name='usuarios_ub_latitud_08acfc_idx'),
        ),
    ]
