# Generated by Django 4.1.1 on 2026-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_ubicaciones_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='rol',
            field=models.CharField(default='visitante', max_length=50),
        ),
    ]
