# Generated by Django 4.1.1 on 2026-03-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_userapp_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='codigo_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
