# Generated by Django 4.1.1 on 2026-03-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_userapp_codigo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='codigo_user',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
