# Generated by Django 4.1.1 on 2026-03-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_userapp_codigo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='codigo_user',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
