# Generated by Django 4.1.1 on 2026-03-21 17:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_userapp_codigo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='geometria_user',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
