# Generated by Django 4.1.1 on 2025-12-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_ubicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='CALIFICACIONES',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificador', to='usuarios.userapp')),
                ('id_user_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificado', to='usuarios.userapp')),
            ],
        ),
        migrations.CreateModel(
            name='BUSQUEDAS',
            fields=[
                ('id_busqueda', models.AutoField(primary_key=True, serialize=False)),
                ('texto_busqueda', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('num_resultados', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userapp')),
            ],
        ),
    ]
