# Generated by Django 4.1.1 on 2026-01-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_ubicaciones_fecha_actualizacion_and_more'),
        ('interacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to='usuarios.userapp'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='id_user_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to='usuarios.userapp'),
        ),
        migrations.AlterUniqueTogether(
            name='calificaciones',
            unique_together={('id_user', 'id_user_vendedor')},
        ),
    ]
