# Generated by Django 4.1.1 on 2026-04-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0002_alter_calificaciones_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='puntuacion',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='tipo_calificacion',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
