# Generated by Django 4.1.1 on 2026-03-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapas', '0001_initial'),
        ('usuarios', '0012_ubicaciones_geometria_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HISTORIAL_RUTAS',
            fields=[
                ('id_rutas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapas.area')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userapp')),
            ],
        ),
        migrations.AddIndex(
            model_name='historial_rutas',
            index=models.Index(fields=['id_user', 'id_area'], name='rutas_histo_id_user_1238b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historial_rutas',
            unique_together={('id_user', 'id_area')},
        ),
    ]
